//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioNaturaSaveCSV.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditoriaNaturaSaveCSV
    {
        public int IdProceso { get; set; }
        public System.DateTime FechaProceso { get; set; }
        public Nullable<System.DateTime> UltimaFechaProceso { get; set; }
        public string NombreArchivo { get; set; }
        public string RutaArchivo { get; set; }
        public string DescripcionProceso { get; set; }
        public int Estado { get; set; }
        public bool EstadoCodificacion { get; set; }
        public bool EstadoBulk { get; set; }
        public bool EstadoDescarga { get; set; }
    
        public virtual EstadoAuditoriaSaveCSV EstadoAuditoriaSaveCSV { get; set; }
    }
}
